"""Add the versioned pedestrian-network schema.

Revision ID: 0002_pedestrian_network
Revises: 0001_postgis
Create Date: 2026-08-12

Five tables: pilot regions, dataset versions, ingestion runs, graph nodes and
graph edges. The design is versioned throughout — ingestion writes a *new*
dataset and swaps activation, never edits the live network.

Two constraints are worth reading before changing anything here:

* ``uq_dataset_versions_one_active_per_region`` is a partial unique index. It
  makes "two active networks in one region" unrepresentable rather than merely
  discouraged.
* Every accessibility enum is a ``CHECK`` on a text column, not a native
  PostgreSQL enum. Native enums cannot have a value removed and require an
  exclusive lock to extend; a CHECK is altered with ordinary DDL, and this
  vocabulary will change as OSM tagging practice does.

Generated by autogenerate against real PostGIS and verified by a full
downgrade/upgrade round trip.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = "0002_pedestrian_network"
down_revision: str | None = "0001_postgis"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "pilot_regions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column(
            "boundary",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "centre",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("default_zoom", sa.Float(), nullable=False),
        sa.Column("local_projected_crs", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_zoom >= 0 AND default_zoom <= 22",
            name=op.f("ck_pilot_regions_default_zoom_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pilot_regions")),
        sa.UniqueConstraint("slug", name=op.f("uq_pilot_regions_slug")),
    )
    op.create_geospatial_index(
        "ix_pilot_regions_boundary",
        "pilot_regions",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "dataset_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pilot_region_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "ingestion_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "bounds",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("validation_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('osm', 'synthetic')",
            name=op.f("ck_dataset_versions_dataset_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'validating', 'validated', 'active', 'retired', 'failed')",
            name=op.f("ck_dataset_versions_dataset_status"),
        ),
        sa.CheckConstraint(
            "node_count >= 0 AND edge_count >= 0",
            name=op.f("ck_dataset_versions_dataset_counts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["pilot_region_id"],
            ["pilot_regions.id"],
            name=op.f("fk_dataset_versions_pilot_region_id_pilot_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
    )
    op.create_index(
        op.f("ix_dataset_versions_pilot_region_id"),
        "dataset_versions",
        ["pilot_region_id"],
        unique=False,
    )
    op.create_index(
        "ix_dataset_versions_region_status",
        "dataset_versions",
        ["pilot_region_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_dataset_versions_one_active_per_region",
        "dataset_versions",
        ["pilot_region_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_geospatial_table(
        "graph_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("source_node_id", sa.String(length=64), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("raw_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_graph_nodes_dataset_version_id_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_nodes")),
        sa.UniqueConstraint("dataset_version_id", "source_node_id", name="uq_node_identity"),
    )
    op.create_index("ix_graph_nodes_dataset", "graph_nodes", ["dataset_version_id"], unique=False)
    op.create_geospatial_index(
        "ix_graph_nodes_geometry",
        "graph_nodes",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("validation_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name=op.f("ck_ingestion_runs_ingestion_status"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_ingestion_runs_dataset_version_id_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_ingestion_runs_dataset_version_id"),
        "ingestion_runs",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_geospatial_table(
        "graph_edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("source_way_id", sa.String(length=64), nullable=True),
        sa.Column("source_u", sa.String(length=64), nullable=False),
        sa.Column("source_v", sa.String(length=64), nullable=False),
        sa.Column("edge_key", sa.Integer(), nullable=False),
        sa.Column("from_node_id", sa.UUID(), nullable=False),
        sa.Column("to_node_id", sa.UUID(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("length_m", sa.Float(), nullable=False),
        sa.Column("directed", sa.Boolean(), nullable=False),
        sa.Column("highway", sa.String(length=48), nullable=True),
        sa.Column("foot_access", sa.String(length=16), nullable=False),
        sa.Column("general_access", sa.String(length=16), nullable=False),
        sa.Column("steps", sa.String(length=8), nullable=False),
        sa.Column("step_count", sa.Integer(), nullable=True),
        sa.Column("surface", sa.String(length=48), nullable=True),
        sa.Column("surface_class", sa.String(length=16), nullable=False),
        sa.Column("smoothness", sa.String(length=48), nullable=True),
        sa.Column("smoothness_class", sa.String(length=16), nullable=False),
        sa.Column("incline_percent", sa.Float(), nullable=True),
        sa.Column("kerb", sa.String(length=16), nullable=False),
        sa.Column("sidewalk", sa.String(length=32), nullable=True),
        sa.Column("is_crossing", sa.Boolean(), nullable=False),
        sa.Column("crossing_type", sa.String(length=32), nullable=True),
        sa.Column("lit", sa.String(length=8), nullable=False),
        sa.Column("indoor", sa.String(length=8), nullable=False),
        sa.Column("bridge", sa.String(length=8), nullable=False),
        sa.Column("tunnel", sa.String(length=8), nullable=False),
        sa.Column("width_m", sa.Float(), nullable=True),
        sa.Column("raw_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "foot_access IN ('yes', 'designated', 'permissive', 'destination', 'private', 'no', 'unknown')",
            name=op.f("ck_graph_edges_edge_foot_access"),
        ),
        sa.CheckConstraint(
            "general_access IN ('yes', 'designated', 'permissive', 'destination', 'private', 'no', 'unknown')",
            name=op.f("ck_graph_edges_edge_general_access"),
        ),
        sa.CheckConstraint(
            "kerb IN ('lowered', 'flush', 'raised', 'none', 'unknown')",
            name=op.f("ck_graph_edges_edge_kerb"),
        ),
        sa.CheckConstraint(
            "smoothness_class IN ('excellent', 'good', 'intermediate', 'bad', 'unknown')",
            name=op.f("ck_graph_edges_edge_smoothness_class"),
        ),
        sa.CheckConstraint(
            "steps IN ('yes', 'no', 'unknown')", name=op.f("ck_graph_edges_edge_steps")
        ),
        sa.CheckConstraint(
            "surface_class IN ('paved', 'compacted', 'rough', 'unknown')",
            name=op.f("ck_graph_edges_edge_surface_class"),
        ),
        sa.CheckConstraint("length_m > 0", name=op.f("ck_graph_edges_edge_length_positive")),
        sa.CheckConstraint(
            "step_count IS NULL OR step_count >= 0",
            name=op.f("ck_graph_edges_edge_step_count_non_negative"),
        ),
        sa.CheckConstraint(
            "width_m IS NULL OR width_m > 0", name=op.f("ck_graph_edges_edge_width_positive")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_graph_edges_dataset_version_id_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["from_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_from_node_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_to_node_id_graph_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_edges")),
        sa.UniqueConstraint(
            "dataset_version_id", "source_u", "source_v", "edge_key", name="uq_edge_identity"
        ),
    )
    op.create_index("ix_graph_edges_dataset", "graph_edges", ["dataset_version_id"], unique=False)
    op.create_index("ix_graph_edges_from_node", "graph_edges", ["from_node_id"], unique=False)
    op.create_geospatial_index(
        "ix_graph_edges_geometry",
        "graph_edges",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index("ix_graph_edges_to_node", "graph_edges", ["to_node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_graph_edges_to_node", table_name="graph_edges")
    op.drop_geospatial_index(
        "ix_graph_edges_geometry",
        table_name="graph_edges",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_index("ix_graph_edges_from_node", table_name="graph_edges")
    op.drop_index("ix_graph_edges_dataset", table_name="graph_edges")
    op.drop_geospatial_table("graph_edges")
    op.drop_index(op.f("ix_ingestion_runs_dataset_version_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_geospatial_index(
        "ix_graph_nodes_geometry",
        table_name="graph_nodes",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_index("ix_graph_nodes_dataset", table_name="graph_nodes")
    op.drop_geospatial_table("graph_nodes")
    op.drop_index(
        "uq_dataset_versions_one_active_per_region",
        table_name="dataset_versions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_dataset_versions_region_status", table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_pilot_region_id"), table_name="dataset_versions")
    op.drop_geospatial_table("dataset_versions")
    op.drop_geospatial_index(
        "ix_pilot_regions_boundary",
        table_name="pilot_regions",
        postgresql_using="gist",
        column_name="boundary",
    )
    op.drop_geospatial_table("pilot_regions")
    # ### end Alembic commands ###
