"""Pedestrian directionality, node evidence and elevation provenance.

Revision ID: 0003_directional_evidence
Revises: 0002_pedestrian_network
Create Date: 2026-08-16

Three corrections that only matter once the network is real.

**Directionality.** `directed` is replaced by `foot_forward` / `foot_backward`.
One boolean cannot say *which* way a segment runs, and the difference decides
whether somebody can walk back out. A CHECK keeps at least one direction open:
a segment nobody may walk either way is a tagging mistake, not a wall, and
deleting the connection produces a phantom "no route".

**Node evidence.** Kerbs are mapped on OSM nodes, not ways, so `tactile_paving`
and `kerb_from_node` record what a crossing inherited from its endpoints and
where that came from.

**Elevation provenance.** `elevation_m` alone is a bare number. The source,
dataset, resolution and acquisition time are what let a derived grade be traced
back to something a person can judge — and `derived_grade_percent` is kept
separate from `incline_percent` so an inference from a terrain model never
overwrites a surveyor's assertion.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_directional_evidence"
down_revision: str | None = "0002_pedestrian_network"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: New NOT NULL columns are added with a temporary server default so existing
#: rows can be backfilled in one statement, then the default is dropped so the
#: schema matches the models exactly. Every default below is the *permissive*
#: value: an existing segment is two-way, has no recorded tactile paving, and
#: inherited nothing from a node — none of which invents evidence.
_BACKFILL: tuple[tuple[str, str, sa.types.TypeEngine[object], str], ...] = (
    ("graph_edges", "foot_forward", sa.Boolean(), "true"),
    ("graph_edges", "foot_backward", sa.Boolean(), "true"),
    ("graph_edges", "ambiguous_direction", sa.Boolean(), "false"),
    ("graph_edges", "vehicle_oneway_ignored", sa.Boolean(), "false"),
    ("graph_edges", "conveying", sa.String(length=20), "'none'"),
    ("graph_edges", "tactile_paving", sa.String(length=8), "'unknown'"),
    ("graph_edges", "kerb_from_node", sa.Boolean(), "false"),
    ("graph_edges", "conflicting_attributes", postgresql.JSONB(astext_type=sa.Text()), "'[]'"),
)


def upgrade() -> None:
    for table, column, column_type, default in _BACKFILL:
        op.add_column(
            table,
            sa.Column(column, column_type, nullable=False, server_default=sa.text(default)),
        )
        op.alter_column(table, column, server_default=None)

    op.add_column(
        "graph_edges", sa.Column("direction_reason", sa.String(length=200), nullable=True)
    )
    op.add_column("graph_edges", sa.Column("derived_grade_percent", sa.Float(), nullable=True))
    op.create_check_constraint(
        op.f("ck_graph_edges_edge_tactile_paving"),
        "graph_edges",
        "tactile_paving IN ('yes', 'no', 'unknown')",
    )
    op.create_check_constraint(
        op.f("ck_graph_edges_edge_walkable_in_some_direction"),
        "graph_edges",
        "foot_forward OR foot_backward",
    )
    op.drop_column("graph_edges", "directed")
    op.add_column("graph_nodes", sa.Column("elevation_source", sa.String(length=64), nullable=True))
    op.add_column(
        "graph_nodes", sa.Column("elevation_dataset", sa.String(length=120), nullable=True)
    )
    op.add_column("graph_nodes", sa.Column("elevation_resolution_m", sa.Float(), nullable=True))
    op.add_column(
        "graph_nodes", sa.Column("elevation_acquired_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graph_nodes", "elevation_acquired_at")
    op.drop_column("graph_nodes", "elevation_resolution_m")
    op.drop_column("graph_nodes", "elevation_dataset")
    op.drop_column("graph_nodes", "elevation_source")
    # Restored with the same temporary-default trick the upgrade uses, and with
    # the value the old column carried: every segment was two-way, because the
    # old importer collapsed the graph to undirected. Reversing this migration
    # genuinely loses which way an escalator ran — that information does not
    # exist in the old shape, and pretending otherwise would be worse.
    op.add_column(
        "graph_edges",
        sa.Column(
            "directed",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("graph_edges", "directed", server_default=None)
    op.drop_constraint(
        op.f("ck_graph_edges_edge_walkable_in_some_direction"), "graph_edges", type_="check"
    )
    op.drop_constraint(op.f("ck_graph_edges_edge_tactile_paving"), "graph_edges", type_="check")
    op.drop_column("graph_edges", "conflicting_attributes")
    op.drop_column("graph_edges", "derived_grade_percent")
    op.drop_column("graph_edges", "kerb_from_node")
    op.drop_column("graph_edges", "tactile_paving")
    op.drop_column("graph_edges", "conveying")
    op.drop_column("graph_edges", "vehicle_oneway_ignored")
    op.drop_column("graph_edges", "ambiguous_direction")
    op.drop_column("graph_edges", "direction_reason")
    op.drop_column("graph_edges", "foot_backward")
    op.drop_column("graph_edges", "foot_forward")
    # ### end Alembic commands ###
