"""Perception: image datasets, labels, model versions and predictions.

Revision ID: 0006_perception
Revises: 0005_kerb_tiers
Create Date: 2026-08-23

Four tables, and one structural decision worth stating at the schema level:
**predictions get their own table rather than columns on `graph_edges`**.

Writing a model's belief onto the same row that holds a surveyor's assertion
would make the two indistinguishable to any query that forgot to check a flag,
and no naming convention survives a column that both can write to. Keeping them
apart is what lets a route say "OpenStreetMap records stairs here" and "a model
thinks there are stairs here" as two different sentences.

`segment_predictions` keys to a segment by its stable source identity — dataset
version plus the OSM node pair — rather than by row id, so a prediction survives
re-ingesting the network.

Images are not stored. `dataset_images` is a manifest: provenance, licence,
checksum, geographic split. The bytes stay wherever they were licensed from, and
out of Git.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = "0006_perception"
down_revision: str | None = "0005_kerb_tiers"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_datasets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("source_doi", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("licence", sa.String(length=64), nullable=False),
        sa.Column("licence_url", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=False),
        sa.Column("commercial_use_permitted", sa.Boolean(), nullable=False),
        sa.Column("share_alike", sa.Boolean(), nullable=False),
        sa.Column("provenance_note", sa.Text(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("image_count", sa.Integer(), nullable=False),
        sa.Column("manifest_checksum", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_image_datasets_image_dataset_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_datasets")),
        sa.UniqueConstraint("name", "version", name="uq_image_dataset_version"),
    )
    op.create_geospatial_table(
        "dataset_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("source_image_id", sa.String(length=200), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("split", sa.String(length=16), nullable=False),
        sa.Column("split_cell", sa.String(length=32), nullable=True),
        sa.Column("quality_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "split IN ('train', 'validation', 'test', 'excluded')",
            name=op.f("ck_dataset_images_image_split"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["image_datasets.id"],
            name=op.f("fk_dataset_images_dataset_id_image_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_images")),
        sa.UniqueConstraint("dataset_id", "source_image_id", name="uq_dataset_image_identity"),
    )
    op.create_index("ix_dataset_images_dataset", "dataset_images", ["dataset_id"], unique=False)
    op.create_geospatial_index(
        "ix_dataset_images_location",
        "dataset_images",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "ix_dataset_images_split", "dataset_images", ["dataset_id", "split"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("prediction_type", sa.String(length=16), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=True),
        sa.Column("code_sha", sa.String(length=64), nullable=True),
        sa.Column("architecture", sa.String(length=120), nullable=True),
        sa.Column("pretrained_weights", sa.String(length=200), nullable=True),
        sa.Column("training_run", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calibration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promotion_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "prediction_type IN ('stairs')", name=op.f("ck_model_versions_model_prediction_type")
        ),
        sa.CheckConstraint(
            "state IN ('candidate', 'validated', 'active', 'retired')",
            name=op.f("ck_model_versions_model_state"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_model_versions_model_version_positive")),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["image_datasets.id"],
            name=op.f("fk_model_versions_dataset_id_image_datasets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name="uq_model_version"),
    )
    op.create_index(
        "uq_one_active_model_per_type",
        "model_versions",
        ["prediction_type"],
        unique=True,
        postgresql_where=sa.text("state = 'active'"),
    )
    op.create_table(
        "image_labels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("review_state", sa.String(length=16), nullable=False),
        sa.Column("labelled_by", sa.String(length=120), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "label IN ('stairs', 'not_stairs', 'ambiguous', 'unusable')",
            name=op.f("ck_image_labels_image_label_class"),
        ),
        sa.CheckConstraint(
            "review_state IN ('unreviewed', 'confirmed', 'disputed', 'corrected')",
            name=op.f("ck_image_labels_image_label_review"),
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["dataset_images.id"],
            name=op.f("fk_image_labels_image_id_dataset_images"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_labels")),
    )
    op.create_index("ix_image_labels_image", "image_labels", ["image_id"], unique=False)
    op.create_table(
        "segment_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("prediction_type", sa.String(length=16), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("source_u", sa.String(length=64), nullable=False),
        sa.Column("source_v", sa.String(length=64), nullable=False),
        sa.Column("edge_key", sa.Integer(), nullable=False),
        sa.Column("raw_probability", sa.Float(), nullable=False),
        sa.Column("calibrated_probability", sa.Float(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=True),
        sa.Column("image_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "prediction_type IN ('stairs')", name=op.f("ck_segment_predictions_prediction_type")
        ),
        sa.CheckConstraint(
            "calibrated_probability >= 0 AND calibrated_probability <= 1",
            name=op.f("ck_segment_predictions_prediction_calibrated_probability"),
        ),
        sa.CheckConstraint(
            "raw_probability >= 0 AND raw_probability <= 1",
            name=op.f("ck_segment_predictions_prediction_raw_probability"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_segment_predictions_dataset_version_id_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["dataset_images.id"],
            name=op.f("fk_segment_predictions_image_id_dataset_images"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_segment_predictions_model_version_id_model_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segment_predictions")),
        sa.UniqueConstraint(
            "model_version_id",
            "dataset_version_id",
            "source_u",
            "source_v",
            "edge_key",
            "prediction_type",
            name="uq_prediction_identity",
        ),
    )
    op.create_index(
        "ix_segment_predictions_lookup",
        "segment_predictions",
        ["dataset_version_id", "prediction_type", "source_u", "source_v"],
        unique=False,
    )
    op.drop_constraint(op.f("ck_graph_edges_edge_incline_direction"), "graph_edges", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_graph_edges_edge_incline_direction"),
        "graph_edges",
        "incline_direction::text = ANY (ARRAY['up'::character varying, 'down'::character varying, 'unknown'::character varying]::text[])",
    )
    op.drop_index("ix_segment_predictions_lookup", table_name="segment_predictions")
    op.drop_table("segment_predictions")
    op.drop_index("ix_image_labels_image", table_name="image_labels")
    op.drop_table("image_labels")
    op.drop_index(
        "uq_one_active_model_per_type",
        table_name="model_versions",
        postgresql_where=sa.text("state = 'active'"),
    )
    op.drop_table("model_versions")
    op.drop_index("ix_dataset_images_split", table_name="dataset_images")
    op.drop_geospatial_index(
        "ix_dataset_images_location",
        table_name="dataset_images",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_index("ix_dataset_images_dataset", table_name="dataset_images")
    op.drop_geospatial_table("dataset_images")
    op.drop_table("image_datasets")
    # ### end Alembic commands ###
